import type { Metadata } from "next";
import {
  SidebarProvider,
  SidebarTrigger,
} from "@components/components/ui/sidebar";
import { AppSidebar } from "@components/components/customComponents/sidebar/SideBar";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Session from "../context/Session";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Session>
        <body
          className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} antialiased`}
        >
          <SidebarProvider>
            <AppSidebar />
            <SidebarTrigger />
            {children}
          </SidebarProvider>
        </body>
      </Session>
    </html>
  );
}
